
project:
  type: book

book:
  title: "Bioinformatics 2"
  author: "Fabricio Almeida-Silva"
  date: "2025"
  chapters:
    - index.qmd
    - chapters/phylogenomics.qmd
    - chapters/gene_set_enrichment.qmd
    
bibliography: bibliography.bib

execute:
  freeze: auto
  warning: false

format:
  html:
    theme: cosmo

editor: 
  mode: source