
# Preface {.unnumbered}

This book aims to provide learners with a hands-on introduction to
topics in Bioinformatics, and the materials here are used in the practical 
lessons of the course **C000500A - Bioinformatics 2** at Ghent University.

Each book chapter represents the contents of a practical lesson from 
the UGent courses, and they serve both as a guide during the lessons and 
as a reference to go back later.

The book will cover:

1. Phylogenomics
2. Gene set enrichment

## Setup

To run the code in this book, you will need to install:

1.  R (\>=4.2.0): go to the [CRAN website](https://cran.r-project.org/), choose your OS (Windows, Linux, or macOS), and follow the installation instructions.

2.  RStudio Desktop: go to the [RStudio website](https://posit.co/download/rstudio-desktop/) and download the installer for your OS.

3.  IQ-TREE 2: go to the [IQ-TREE download page](http://www.iqtree.org/#download) and follow the installation instructions for your OS.

After installing R and RStudio, you will need to install some required R 
packages. To do that, open RStudio and execute the code below in your console:

```{r}
#| eval: false

# Install BiocManager
install.packages("BiocManager")

# Use {BiocManager} to install required packages (if they are not installed)
packages <- c(
    "here", 
    "cogeqc",
    "Biostrings", 
    "tidyverse", 
    "ape",
    "msa", 
    "tidyverse",
    "SummarizedExperiment",
    "DESeq2",
    "clusterProfiler",
    "enrichplot",
    "org.Mm.eg.db",
    "universalmotif"
)

BiocManager::install(packages)
```

After that, you should have everything ready.
